Wrong capitalisation on `process.env`
clusterio/clusterio pull request #436
Opened 2021-12-07 10:39 UTC by jake-87

2021-12-07 10:45 UTC, jake-87 commented
Apologies that these slipped through, as far as I can tell, they were misspelled while doing final bugfixes in the Github online editor, hence why they were not caught. I am working on unit tests for these systems, but it is more complicated due to the interactive nature of the system.

2021-12-07 11:05 UTC, Danielv123 requested changes

2021-12-07 11:05 UTC, Danielv123 commented on packages/ctl/ctl.js
> +	for (let group of serlializedConfig.groups) {
Why did you add a new typo?

2021-12-07 11:15 UTC, Danielv123 approved these changes
Should be squash-merged

2021-12-08 23:04 UTC, psihius approved these changes
And this is why I run an IDE with a spell checker :100:

2021-12-08 23:04 UTC, merged